version: '3.8'

services:
  frontend:
    container_name: exalty-frontend
    build:
      context: ./exalty-frontend
      dockerfile: Dockerfile
    # image: worhu/exalty-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./exalty-frontend:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - exalty-network

  api:
    container_name: exalty-backend
    build:
      context: ./exalty-backend
      dockerfile: Dockerfile
    # image: worhu/exalty-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./exalty-backend:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - exalty-network

  db:
    container_name: exalty_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exalty_db-dev
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - exalty-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    container_name: exalty-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - exalty-network

networks:
  exalty-network:
    driver: bridge

volumes:
  db-data:
